import Head from 'next/head'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'
import Carousel from '@/components/Carousel'

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Mr. G</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.mt} ${styles.flexColumnCenter}`}>
        <h1 className={styles.font}>I&apos;m Mr. G.</h1>
        <Link className={styles.fontSmaller} href="/about">
          About me
        </Link>

        <h1>Projects</h1>

        {data ? (
          <Carousel data={data} />
        ) : (
          <h1>No repo data yet...(probally because got rate limited)</h1>
        )}
      </div>
    </>
  )
}

export async function getStaticProps() {
  const response = await fetch(
    'https://api.github.com/users/Iampersoncool/repos'
  )
  const json = await response.json()

  if (!response.ok) {
    return {
      props: {
        data: null,
      },
    }
  }

  return {
    props: {
      data: json,
    },
  }
}
