import Head from 'next/head'
import Link from 'next/link'
import sampleGithubData from '@/utils/sampleGithubData'
import styles from '@/styles/Home.module.css'
import Carousel from '@/components/Carousel'
import { useEffect, useState } from 'react'

export default function Home() {
  const [repoData, setRepoData] = useState(null)

  useEffect(() => {
    if (process.env.NODE_ENV === 'development') {
      console.log('development')
      setRepoData(sampleGithubData)
      return
    }

    console.log('production')

    fetch('https://api.github.com/users/Iampersoncool/repos')
      .then((res) => res.json())
      .then((data) => {
        setRepoData(data)
      })
      .catch(console.error)
  }, [])

  useEffect(() => {
    console.log(repoData)
  }, [repoData])

  return (
    <>
      <Head>
        <title>Mr. G</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.mt} ${styles.flexColumnCenter}`}>
        <h1 className={styles.font}>I&apos;m Mr. G.</h1>
        <Link className={styles.fontSmaller} href="/about">
          About me
        </Link>

        <h1>Projects</h1>

        {repoData ? (
          <Carousel data={repoData} />
        ) : (
          <h1>Loading repo data...</h1>
        )}
      </div>
    </>
  )
}
